-- เพิ่มข้อมูลผลงานรายวิชาจริงลงในตาราง student_works สำหรับการตั้งค่าและตรวจสอบหน้า Course Works
-- เมื่อรันไฟล์นี้ใน Supabase SQL Editor ระบบจะ insert/upsert 3 records จริง
-- ไฟล์นี้ไม่เปลี่ยน schema และควรรันด้วยตนเองเมื่อพร้อมเท่านั้น

insert into student_works (
  id,
  title,
  description,
  category,
  academic_year,
  work_type,
  course_id,
  course_name,
  students,
  advisor_name,
  technologies,
  image_url,
  image_alt,
  pdf_url,
  pdf_filename,
  project_url,
  external_url,
  source_type,
  source_system,
  sort_order,
  is_featured,
  is_active,
  slug
) values
(
  '7c9c1dd7-f6d8-48f2-81e5-0f90f8c73f51',
  'ระบบจัดการคลังอุปกรณ์ไอที',
  'เว็บแอปสำหรับบันทึกครุภัณฑ์ ยืมคืนอุปกรณ์ และสรุปรายงานคงเหลือของห้องปฏิบัติการไอที',
  'Database Application',
  '2567',
  'course',
  '09-142-205',
  'ระบบจัดการฐานข้อมูล',
  array['กิตติพงศ์ แสงดี', 'ปวีณา ใจมั่น'],
  'อ.นภัส วัฒนาระบบ',
  array['PostgreSQL', 'Next.js', 'Tailwind CSS'],
  null,
  'ระบบจัดการคลังอุปกรณ์ไอที',
  null,
  null,
  null,
  null,
  'internal',
  null,
  101,
  false,
  true,
  'it-equipment-inventory-course-work'
),
(
  '2d679d47-7054-41a6-b812-fc94463c08ac',
  'เว็บจองคิวปรึกษาอาจารย์',
  'ระบบจองเวลาพบอาจารย์ ตรวจสอบช่วงเวลาว่าง และแจ้งสถานะนัดหมายสำหรับนักศึกษาในรายวิชา',
  'Web Application',
  '2567',
  'course',
  '09-142-306',
  'การพัฒนาเว็บยุคใหม่',
  array['ธนวัฒน์ พูลสุข', 'อริสา ทองแท้'],
  'อ.สุเมธ พัฒนาเว็บ',
  array['React', 'Supabase', 'TypeScript'],
  null,
  'เว็บจองคิวปรึกษาอาจารย์',
  null,
  null,
  null,
  null,
  'internal',
  null,
  102,
  false,
  true,
  'advisor-appointment-booking-course-work'
),
(
  '6a5836bd-b7f4-4042-a9dc-d39d7232ea67',
  'ระบบติดตามงานกลุ่มรายวิชา',
  'เว็บแอปสำหรับแบ่งงาน ติดตามความคืบหน้า และสรุปภาระงานของสมาชิกในโครงงานกลุ่มรายวิชา',
  'Software Engineering',
  '2566',
  'course',
  '09-142-394',
  'การบริหารจัดการโครงการเทคโนโลยีสารสนเทศ',
  array['ภัทรพล ศรีสุข', 'ณัฐชา วงศ์วานิช', 'ชลธิชา คงดี'],
  'ดร.วิภา ออกแบบระบบ',
  array['Next.js', 'Prisma', 'PostgreSQL'],
  null,
  'ระบบติดตามงานกลุ่มรายวิชา',
  null,
  null,
  null,
  null,
  'internal',
  null,
  103,
  false,
  true,
  'team-task-tracking-course-work'
)
on conflict (id) do update set
  title = excluded.title,
  description = excluded.description,
  category = excluded.category,
  academic_year = excluded.academic_year,
  work_type = excluded.work_type,
  course_id = excluded.course_id,
  course_name = excluded.course_name,
  students = excluded.students,
  advisor_name = excluded.advisor_name,
  technologies = excluded.technologies,
  image_url = excluded.image_url,
  image_alt = excluded.image_alt,
  pdf_url = excluded.pdf_url,
  pdf_filename = excluded.pdf_filename,
  project_url = excluded.project_url,
  external_url = excluded.external_url,
  source_type = excluded.source_type,
  source_system = excluded.source_system,
  sort_order = excluded.sort_order,
  is_featured = excluded.is_featured,
  is_active = excluded.is_active,
  slug = excluded.slug;
